# RAG System Configuration

# LLM Configuration
llm:
  provider: "groq"
  model: "llama-3.1-8b-instant"
  temperature: 0.7
  max_tokens: 1000

# Embedding Configuration
embeddings:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  device: "cpu"

# Vector Database Configuration
vector_db:
  provider: "chromadb"
  path: "./data/vectors"
  collection_name: "documents"
  distance_metric: "cosine"

# Text Splitting Configuration
text_splitter:
  chunk_size: 1000
  chunk_overlap: 200
  separators: ["\n\n", "\n", " ", ""]

# Retrieval Configuration
retrieval:
  max_results: 5
  score_threshold: 0.7
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(name)s.%(funcName)s:%(lineno)d - %(message)s"
  path: "./logs" 